### ISSUE TITLE
Unknown chef error when initializing NAT in SSH_Inception

### ISSUE THREAD

**Issue by newjam** [edurange/edurange-server#49]
A user reported at Monday, March 18, 2019 9:53 AM "I tried to test out the ssh_inception scenario today; I created it and tried to boot, but the status remained at "booted_partial" with no further info about the NAT instance given and the boot log (attached) seems to indicate a failure.  Do you have any idea from this limited info what might be going wrong or what I might be doing wrong to get the scenario up and running?  Thanks!"

Here is the boot log provided by a user. 

```
 SSH_Inception: boot log
SSH_Inception: BEGIN: status={"SSH_Inception"=>"stopped", "Cloud1"=>"stopped", "SubnetNAT"=>"stopped", "PlayerSubnet"=>"stopped", "NAT"=>"stopped", "AnonFTP"=>"stopped", "SatansPalace"=>"stopped", "FifthStop"=>"stopped", "FourthStop"=>"stopped", "ThirdStop"=>"stopped", "SecondStop"=>"stopped", "FirstStop"=>"stopped", "StartingLine"=>"stopped"} time=1552957865
SSH_Inception: validating options: opts={:background=>true, :action=>:boot, :console_print=>true, :pretend=>false, :boot_code=>"19-03-19-01-11-05_849e2d4e", :resources=>{"Cloud1"=>{:action=>:boot, :pretend=>false, :background=>true, :wait=>0}, "SubnetNAT"=>{:action=>:boot, :pretend=>false, :background=>true, :wait=>0}, "PlayerSubnet"=>{:action=>:boot, :pretend=>false, :background=>true, :wait=>0}, "NAT"=>{:action=>:boot, :pretend=>false, :background=>true, :wait=>0}, "AnonFTP"=>{:action=>:boot, :pretend=>false, :background=>true, :wait=>0}, "SatansPalace"=>{:action=>:boot, :pretend=>false, :background=>true, :wait=>0}, "FifthStop"=>{:action=>:boot, :pretend=>false, :background=>true, :wait=>0}, "FourthStop"=>{:action=>:boot, :pretend=>false, :background=>true, :wait=>0}, "ThirdStop"=>
{:action=>:boot, :pretend=>false, :background=>true, :wait=>0}, "SecondStop"=>{:action=>:boot, :pretend=>false, :background=>true, :wait=>0}, "FirstStop"=>{:action=>:boot, :pretend=>false, :background=>true, :wait=>0}, "StartingLine"=>{:action=>:boot, :pretend=>false, :background=>true, :wait=>0}}}
SSH_Inception: scheduled ["Cloud1", "SubnetNAT", "PlayerSubnet", "NAT", "AnonFTP", "SatansPalace", "FifthStop", "FourthStop", "ThirdStop", "SecondStop", "FirstStop", "StartingLine"]
SSH_Inception: boot "Cloud1": background=true
SSH_Inception: {:_serializing_datatype=>"Symbol", :value=>"boot"} "SubnetNAT": background=true
SSH_Inception: {:_serializing_datatype=>"Symbol", :value=>"boot"} "PlayerSubnet": background=true
SSH_Inception: {:_serializing_datatype=>"Symbol", :value=>"boot"} "NAT": background=true
Cloud1: BEGIN: opts={:action=>:boot, :pretend=>false, :background=>true, :wait=>0, :obj=>#} time=1552957865
SSH_Inception: {:_serializing_datatype=>"Symbol", :value=>"boot"} "AnonFTP": background=true
Cloud1: getting boot lock
SSH_Inception: {:_serializing_datatype=>"Symbol", :value=>"boot"} "SatansPalace": background=true
Cloud1: AWS: creating VPC
SSH_Inception: {:_serializing_datatype=>"Symbol", :value=>"boot"} "FifthStop": background=true
SubnetNAT: BEGIN: opts={:action=>:boot, :pretend=>false, :background=>true, :wait=>0, :obj=>#} time=1552957865
SubnetNAT: getting boot lock
SSH_Inception: {:_serializing_datatype=>"Symbol", :value=>"boot"} "FourthStop": background=true
PlayerSubnet: BEGIN: opts={:action=>:boot, :pretend=>false, :background=>true, :wait=>0, :obj=>#} time=1552957865
PlayerSubnet: getting boot lock
SubnetNAT: wait for parent to finish booting
SSH_Inception: {:_serializing_datatype=>"Symbol", :value=>"boot"} "ThirdStop": background=true
SubnetNAT: waiting up to 600s for 'Cloud1' to finish booting
NAT: BEGIN: opts={:action=>:boot, :pretend=>false, :background=>true, :wait=>0, :obj=>#} time=1552957865
NAT: getting boot lock
SSH_Inception: {:_serializing_datatype=>"Symbol", :value=>"boot"} "SecondStop": background=true
AnonFTP: BEGIN: opts={:action=>:boot, :pretend=>false, :background=>true, :wait=>0, :obj=>#} time=1552957865
PlayerSubnet: wait for parent to finish booting
PlayerSubnet: waiting up to 600s for 'Cloud1' to finish booting
AnonFTP: getting boot lock
NAT: wait for parent to finish booting
SatansPalace: BEGIN: opts={:action=>:boot, :pretend=>false, :background=>true, :wait=>0, :obj=>#} time=1552957865
NAT: waiting up to 600s for 'SubnetNAT' to finish booting
SSH_Inception: {:_serializing_datatype=>"Symbol", :value=>"boot"} "FirstStop": background=true
AnonFTP: wait for parent to finish booting
SatansPalace: getting boot lock
AnonFTP: waiting up to 600s for 'PlayerSubnet' to finish booting
SSH_Inception: {:_serializing_datatype=>"Symbol", :value=>"boot"} "StartingLine": background=true
FifthStop: BEGIN: opts={:action=>:boot, :pretend=>false, :background=>true, :wait=>0, :obj=>#} time=1552957865
SatansPalace: wait for parent to finish booting
FifthStop: getting boot lock
SatansPalace: waiting up to 600s for 'PlayerSubnet' to finish booting
FourthStop: BEGIN: opts={:action=>:boot, :pretend=>false, :background=>true, :wait=>0, :obj=>#} time=1552957865
FourthStop: getting boot lock
SSH_Inception: waiting for descendent "Cloud1" to finish: status=stopped
FifthStop: wait for parent to finish booting
FourthStop: wait for parent to finish booting
ThirdStop: BEGIN: opts={:action=>:boot, :pretend=>false, :background=>true, :wait=>0, :obj=>#} time=1552957865
FourthStop: waiting up to 600s for 'PlayerSubnet' to finish booting
FifthStop: waiting up to 600s for 'PlayerSubnet' to finish booting
ThirdStop: getting boot lock
ThirdStop: wait for parent to finish booting
ThirdStop: waiting up to 600s for 'PlayerSubnet' to finish booting
Cloud1: AWS: created VPC 'vpc-0d94563e6eaf0cf4c'
Cloud1: AWS: waiting for VPC 'vpc-0d94563e6eaf0cf4c' status to change to ':available'
Cloud1: AWS: creating default tags for VPC 'vpc-0d94563e6eaf0cf4c'
Cloud1: AWS: creating InternetGateway
Cloud1: AWS: created InternetGateway 'igw-0c8b1d04ca57643c1'
Cloud1: AWS: getting VPC 'vpc-0d94563e6eaf0cf4c' SecurityGroup
Cloud1: AWS: creating rules for SecurityGroup 'sg-00a09c9f27510816d'
Cloud1: SUCCESS: status=booted time=1552957868
SecondStop: BEGIN: opts={:action=>:boot, :pretend=>false, :background=>true, :wait=>0, :obj=>#} time=1552957868
SecondStop: getting boot lock
SecondStop: wait for parent to finish booting
SecondStop: waiting up to 600s for 'PlayerSubnet' to finish booting
SubnetNAT: AWS: creating Subnet
PlayerSubnet: AWS: creating Subnet
SSH_Inception: waiting for descendent "SubnetNAT" to finish: status=stopped
SubnetNAT: AWS: created Subnet 'subnet-05f9be19bb7582acf'
SubnetNAT: AWS: waiting for Subnet 'subnet-05f9be19bb7582acf' to become available
SubnetNAT: AWS: waiting for Subnet 'subnet-05f9be19bb7582acf' status to change to ':available'
SubnetNAT: AWS: creating default tags for Subnet 'subnet-05f9be19bb7582acf'
PlayerSubnet: AWS: created Subnet 'subnet-0997d89db585debdc'
PlayerSubnet: AWS: waiting for Subnet 'subnet-0997d89db585debdc' to become available
PlayerSubnet: AWS: waiting for Subnet 'subnet-0997d89db585debdc' status to change to ':available'
PlayerSubnet: AWS: creating default tags for Subnet 'subnet-0997d89db585debdc'
SubnetNAT: AWS: creating RouteTable for 'subnet-05f9be19bb7582acf'
SubnetNAT: AWS: assigned RouteTable 'rtb-0d17851c3adc59e1e' to 'subnet-05f9be19bb7582acf'
PlayerSubnet: AWS: creating RouteTable for 'subnet-0997d89db585debdc'
SubnetNAT: AWS: getting Subnet 'subnet-05f9be19bb7582acf' VPC 'vpc-0d94563e6eaf0cf4c'
PlayerSubnet: AWS: assigned RouteTable 'rtb-06711fdfca0ad15ad' to 'subnet-0997d89db585debdc'
SubnetNAT: SUCCESS: status=booted time=1552957871
FirstStop: BEGIN: opts={:action=>:boot, :pretend=>false, :background=>true, :wait=>0, :obj=>#} time=1552957871
FirstStop: getting boot lock
FirstStop: wait for parent to finish booting
FirstStop: waiting up to 600s for 'PlayerSubnet' to finish booting
PlayerSubnet: AWS: getting Subnet 'subnet-0997d89db585debdc' VPC 'vpc-0d94563e6eaf0cf4c'
PlayerSubnet: SUCCESS: status=booted time=1552957871
StartingLine: BEGIN: opts={:action=>:boot, :pretend=>false, :background=>true, :wait=>0, :obj=>#} time=1552957871
StartingLine: getting boot lock
StartingLine: wait for parent to finish booting
StartingLine: waiting up to 600s for 'PlayerSubnet' to finish booting
StartingLine: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_StartingLine_4940_5c12b6_exit_status'
StartingLine: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_StartingLine_4940_5c12b6_exit_status'
StartingLine: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_StartingLine_4940_5c12b6_script_log'
SecondStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_SecondStop_4942_2e2736_exit_status'
StartingLine: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_StartingLine_4940_5c12b6_script_log'
StartingLine: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_StartingLine_4940_5c12b6_bash_history'
SecondStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_SecondStop_4942_2e2736_exit_status'
StartingLine: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_StartingLine_4940_5c12b6_bash_history'
StartingLine: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_StartingLine_4940_5c12b6_com'
SecondStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_SecondStop_4942_2e2736_script_log'
StartingLine: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_StartingLine_4940_5c12b6_com'
StartingLine: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_StartingLine_4940_5c12b6_com'
SecondStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_SecondStop_4942_2e2736_script_log'
SecondStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_SecondStop_4942_2e2736_bash_history'
SecondStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_SecondStop_4942_2e2736_bash_history'
SecondStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_SecondStop_4942_2e2736_com'
StartingLine: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_StartingLine_4940_5c12b6_cookbook'
SecondStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_SecondStop_4942_2e2736_com'
StartingLine: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_StartingLine_4940_5c12b6_cookbook'
StartingLine: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_StartingLine_4940_5c12b6_cookbook'
SecondStop: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_SecondStop_4942_2e2736_com'
SecondStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_SecondStop_4942_2e2736_cookbook'
SecondStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_SecondStop_4942_2e2736_cookbook'
SecondStop: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_SecondStop_4942_2e2736_cookbook'
SSH_Inception: waiting for descendent "PlayerSubnet" to finish: status=stopped
SSH_Inception: waiting for descendent "NAT" to finish: status=stopped
NAT: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_exit_status'
StartingLine: AWS: creating Instance
AnonFTP: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_AnonFTP_4947_a3997f_exit_status'
FirstStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FirstStop_4941_6193ec_exit_status'
AnonFTP: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_AnonFTP_4947_a3997f_exit_status'
SatansPalace: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_SatansPalace_4946_bec788_exit_status'
FourthStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FourthStop_4944_c3db99_exit_status'
NAT: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_exit_status'
FirstStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FirstStop_4941_6193ec_exit_status'
SatansPalace: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_SatansPalace_4946_bec788_exit_status'
FifthStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FifthStop_4945_e199fc_exit_status'
ThirdStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_ThirdStop_4943_453589_exit_status'
FourthStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FourthStop_4944_c3db99_exit_status'
FifthStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FifthStop_4945_e199fc_exit_status'
ThirdStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_ThirdStop_4943_453589_exit_status'
AnonFTP: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_AnonFTP_4947_a3997f_script_log'
AnonFTP: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_AnonFTP_4947_a3997f_script_log'
FirstStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FirstStop_4941_6193ec_script_log'
NAT: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_script_log'
AnonFTP: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_AnonFTP_4947_a3997f_bash_history'
FourthStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FourthStop_4944_c3db99_script_log'
SatansPalace: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_SatansPalace_4946_bec788_script_log'
FifthStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FifthStop_4945_e199fc_script_log'
ThirdStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_ThirdStop_4943_453589_script_log'
FirstStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FirstStop_4941_6193ec_script_log'
NAT: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_script_log'
AnonFTP: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_AnonFTP_4947_a3997f_bash_history'
FourthStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FourthStop_4944_c3db99_script_log'
SatansPalace: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_SatansPalace_4946_bec788_script_log'
FirstStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FirstStop_4941_6193ec_bash_history'
NAT: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_bash_history'
FifthStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FifthStop_4945_e199fc_script_log'
ThirdStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_ThirdStop_4943_453589_script_log'
AnonFTP: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_AnonFTP_4947_a3997f_com'
SatansPalace: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_SatansPalace_4946_bec788_bash_history'
FourthStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FourthStop_4944_c3db99_bash_history'
FifthStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FifthStop_4945_e199fc_bash_history'
ThirdStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_ThirdStop_4943_453589_bash_history'
FirstStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FirstStop_4941_6193ec_bash_history'
SecondStop: AWS: creating Instance
NAT: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_bash_history'
FourthStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FourthStop_4944_c3db99_bash_history'
ThirdStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_ThirdStop_4943_453589_bash_history'
SatansPalace: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_SatansPalace_4946_bec788_bash_history'
AnonFTP: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_AnonFTP_4947_a3997f_com'
FifthStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FifthStop_4945_e199fc_bash_history'
NAT: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_com'
FirstStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FirstStop_4941_6193ec_com'
AnonFTP: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_AnonFTP_4947_a3997f_com'
FifthStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FifthStop_4945_e199fc_com'
SatansPalace: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_SatansPalace_4946_bec788_com'
FourthStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FourthStop_4944_c3db99_com'
ThirdStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_ThirdStop_4943_453589_com'
NAT: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_com'
NAT: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_com'
FirstStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FirstStop_4941_6193ec_com'
FourthStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FourthStop_4944_c3db99_com'
SatansPalace: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_SatansPalace_4946_bec788_com'
ThirdStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_ThirdStop_4943_453589_com'
FifthStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FifthStop_4945_e199fc_com'
FirstStop: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_FirstStop_4941_6193ec_com'
SatansPalace: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_SatansPalace_4946_bec788_com'
FifthStop: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_FifthStop_4945_e199fc_com'
AnonFTP: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_AnonFTP_4947_a3997f_cookbook'
NAT: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_cookbook'
ThirdStop: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_ThirdStop_4943_453589_com'
FourthStop: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_FourthStop_4944_c3db99_com'
NAT: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_cookbook'
AnonFTP: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_AnonFTP_4947_a3997f_cookbook'
AnonFTP: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_AnonFTP_4947_a3997f_cookbook'
NAT: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_cookbook'
SatansPalace: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_SatansPalace_4946_bec788_cookbook'
FifthStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FifthStop_4945_e199fc_cookbook'
ThirdStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_ThirdStop_4943_453589_cookbook'
FirstStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FirstStop_4941_6193ec_cookbook'
FourthStop: AWS: creating S3 Object 'cloud_Steve_Cole_SSH_Inception_864_FourthStop_4944_c3db99_cookbook'
ThirdStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_ThirdStop_4943_453589_cookbook'
FirstStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FirstStop_4941_6193ec_cookbook'
SatansPalace: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_SatansPalace_4946_bec788_cookbook'
FourthStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FourthStop_4944_c3db99_cookbook'
FifthStop: AWS: getting S3Object url for 'cloud_Steve_Cole_SSH_Inception_864_FifthStop_4945_e199fc_cookbook'
FourthStop: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_FourthStop_4944_c3db99_cookbook'
SatansPalace: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_SatansPalace_4946_bec788_cookbook'
ThirdStop: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_ThirdStop_4943_453589_cookbook'
FifthStop: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_FifthStop_4945_e199fc_cookbook'
FirstStop: AWS: writing to S3Object 'cloud_Steve_Cole_SSH_Inception_864_FirstStop_4941_6193ec_cookbook'
AnonFTP: AWS: creating Instance
NAT: AWS: creating Instance
SecondStop: AWS: created Instance 'i-098b07e835e5676be'
SecondStop: AWS: waiting for Instance 'i-098b07e835e5676be' status to change to ':running'
StartingLine: AWS: created Instance 'i-01ec6b9a924bc3b49'
StartingLine: AWS: waiting for Instance 'i-01ec6b9a924bc3b49' status to change to ':running'
SatansPalace: AWS: creating Instance
FirstStop: AWS: creating Instance
FourthStop: AWS: creating Instance
FifthStop: AWS: creating Instance
ThirdStop: AWS: creating Instance
NAT: AWS: created Instance 'i-0d2ceea6f86be2532'
NAT: AWS: waiting for Instance 'i-0d2ceea6f86be2532' status to change to ':running'
AnonFTP: AWS: created Instance 'i-088f05d8fe6820700'
AnonFTP: AWS: waiting for Instance 'i-088f05d8fe6820700' status to change to ':running'
ThirdStop: AWS: created Instance 'i-0e9b7fe5beb4c8d60'
ThirdStop: AWS: waiting for Instance 'i-0e9b7fe5beb4c8d60' status to change to ':running'
FifthStop: AWS: created Instance 'i-0f48d7943d6a037b6'
FifthStop: AWS: waiting for Instance 'i-0f48d7943d6a037b6' status to change to ':running'
FirstStop: AWS: created Instance 'i-0cc708d9948a7f0e5'
FirstStop: AWS: waiting for Instance 'i-0cc708d9948a7f0e5' status to change to ':running'
SatansPalace: AWS: created Instance 'i-06f6147049a28d1c6'
SatansPalace: AWS: waiting for Instance 'i-06f6147049a28d1c6' status to change to ':running'
FourthStop: AWS: created Instance 'i-009afefebb905e177'
FourthStop: AWS: waiting for Instance 'i-009afefebb905e177' status to change to ':running'
SatansPalace: AWS: creating default tags for Instance 'i-06f6147049a28d1c6'
StartingLine: AWS: creating default tags for Instance 'i-01ec6b9a924bc3b49'
FirstStop: AWS: creating default tags for Instance 'i-0cc708d9948a7f0e5'
NAT: AWS: creating default tags for Instance 'i-0d2ceea6f86be2532'
AnonFTP: AWS: creating default tags for Instance 'i-088f05d8fe6820700'
NAT: AWS: creating ElasticIP for Instance 'i-0d2ceea6f86be2532'
NAT: AWS: created ElasticIP '52.22.176.127'
NAT: AWS: waiting for ElasticIP '52.22.176.127' to exist
NAT: AWS: associating ElastipIP '52.22.176.127' with Instance 'i-0d2ceea6f86be2532'
ThirdStop: AWS: creating default tags for Instance 'i-0e9b7fe5beb4c8d60'
NAT: AWS: creating Route for Subnet 'subnet-05f9be19bb7582acf' to NAT Instance 'i-0d2ceea6f86be2532'
SecondStop: AWS: creating default tags for Instance 'i-098b07e835e5676be'
FourthStop: AWS: creating default tags for Instance 'i-009afefebb905e177'
FifthStop: AWS: creating default tags for Instance 'i-0f48d7943d6a037b6'
NAT: FAIL: RuntimeError Error in chef script
NAT: TRACE
/var/www/edurange/app/models/concerns/provider_aws.rb:291:in `aws_instance_initialized?'
NAT:/var/www/edurange/app/models/concerns/provider_aws.rb:277:in `block in aws_instance_wait_till_initialized'
NAT:/usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
NAT:/usr/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
NAT:/usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
NAT:/usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
NAT:/usr/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
NAT:/var/www/edurange/app/models/concerns/provider_aws.rb:276:in `aws_instance_wait_till_initialized'
NAT:/var/www/edurange/app/models/concerns/provider_aws.rb:226:in `aws_instance_boot'
NAT:/var/www/edurange/app/models/concerns/provider.rb:416:in `boot_descendent_main'
NAT:/var/www/edurange/app/models/concerns/provider.rb:343:in `boot_descendent'
NAT:/var/www/edurange/app/jobs/boot_descendent_job.rb:10:in `perform'
NAT: ECART
NAT: Cleaning up 'NAT'
NAT: AWS: getting Instance 'i-0d2ceea6f86be2532'
NAT: AWS: checking if Instance 'i-0d2ceea6f86be2532' exists
SSH_Inception: descendent "NAT" {:_serializing_datatype=>"Symbol", :value=>"boot"} failed
SSH_Inception: waiting for descendent "AnonFTP" to finish: status=stopped
NAT: AWS: looking for Instance 'i-0d2ceea6f86be2532' ElasticIP
NAT: AWS: disassociating ElasticIP '52.22.176.127'
NAT: AWS: deleting ElasticIP '52.22.176.127'
NAT: AWS: setting Instance 'i-0d2ceea6f86be2532' volumes deleteOnTermination
NAT: AWS: deleting Instance 'i-0d2ceea6f86be2532'
NAT: AWS: waiting for Instance 'i-0d2ceea6f86be2532' status to change to ':terminated'
NAT: AWS: saving bash history from Instance 'NAT'
NAT: AWS: getting S3Object 'name'
NAT: AWS: reading S3Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_bash_history'
NAT: AWS: saving exit status from Instance 'NAT'
NAT: AWS: getting S3Object 'name'
NAT: AWS: reading S3Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_exit_status'
NAT: AWS: saving script log from Instance 'NAT'
NAT: AWS: getting S3Object 'name'
NAT: AWS: reading S3Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_script_log'
NAT: AWS: looking for instance S3 files to delete
NAT: AWS: deleting S3Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_cookbook'
NAT: AWS: deleting S3Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_com'
NAT: AWS: deleting S3Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_bash_history'
NAT: AWS: deleting S3Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_exit_status'
NAT: AWS: deleting S3Object 'cloud_Steve_Cole_SSH_Inception_864_NAT_4939_1efd4a_script_log'
```

**Comment by newjam** [comment]
closing because I can't reproduce and don't have the exception stack trace.
